# .github/workflows/node.js.yml
name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.12 ]
    defaults:
      run:
        working-directory: mj-front
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Lint code
        run: npm run lint
      - run: npm run build --if-present
      # - run: npm test
